// Code generated by cmd/cgo; DO NOT EDIT.

//line /Users/doveone/doveDemo/doveProject/cgo/cgo.go:1:1
package main

/*
int sum(int a, int b){
	return a+b;
}
*/
import _ "unsafe"

func main() {
	println(( /*line :11:10*/ _Cfunc_sum /*line :11:14*/)(1, 1))
}
